//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkDataBaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte
    {
        public int Id { get; set; }
        public string Numero { get; set; }
        public decimal Solde { get; set; }
        public int ClientId { get; set; }
    }
}
